FROM jc21/nginx-proxy-manager:2.11.1

ENV NPM_LANGUAGE="zh"

EXPOSE 80 81 443

RUN  rm -rf /app/frontend /var/www/html/index.html /app/schema /app/templates /app/migrations /app/internal/proxy-host.js
COPY frontend/dist /app/frontend
COPY backend/schema /app/schema
COPY backend/templates /app/templates
COPY backend/migrations /app/migrations
COPY docker/rootfs/var/www/html/index.html /var/www/html/index.html
COPY backend/internal/proxy-host.js /app/internal/proxy-host.js

WORKDIR /app

VOLUME [ "/data", "/etc/letsencrypt" ]
ENTRYPOINT [ "/init" ]

LABEL org.label-schema.schema-version="1.0" \
	org.label-schema.license="MIT" \
	org.label-schema.name="nginx-proxy-manager-monitor-zh" \
	org.label-schema.description="Docker container for managing Nginx proxy hosts with a simple, powerful interface " \
	org.label-schema.url="https://github.com/2691432189/nginx-proxy-manager-monitor-zh" \
	org.label-schema.vcs-url="https://github.com/2691432189/nginx-proxy-manager-monitor-zh" \
	org.label-schema.cmd="docker run --rm -ti 2691432189/nginx-proxy-manager-monitor-zh"
