#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/ci/frontend-build"

cd "${DIR}/../.."

docker build -t 2691432189/nginx-proxy-manager-monitor-zh:2.10.4 -f docker/Dockerfile-zh .
